### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by NovaGL** [Iture/MusicCastControl#1]
This is the app I have been looking for, was trying to do it myself but this might be better.

How do I set it up?

**Comment by Iture** [comment]
I'll write little more later, but you need Python 3.x, Tornado and paho-mqtt library. Mostly that's all and it just works

**Comment by NovaGL** [comment]
Can you please update me on this. It still doesn't work for me

**Comment by NovaGL** [comment]
Sound program list keep crashing the app so I deleted that line from the API and it worked. If you could still look into this that would be great.
